### ISSUE TITLE
是否可以在我的项目中引入您的代码？

### ISSUE THREAD

**Issue by Jinky-X** [GaGaChina/mp_gpass_ts#1]
我近期也想开发一个KDBX的微信小程序，但是发现kdbxweb库在小程序环境下很难运行，所以希望引入您的代码。或者如果能添加一个开源许可证就更好了。

**Comment by GaGaChina** [comment]
要加什么开源许可证, 怎么加, 我给你加!

**Comment by Jinky-X** [comment]
许可证的选择看您的想法吧，因为您引用的项目都是MIT许可证的，所以选哪个都可以。我找了一张分支图供您参考。
![图片](https://user-images.githubusercontent.com/56373838/215002492-f1a4b341-ccb1-4edc-a2c4-92c14c928932.png)

---

另外，加许可证的方法我在百度找了一个[CSDN博客](https://blog.csdn.net/weixin_43233914/article/details/121420751)，谢谢大佬分享

**Comment by GaGaChina** [comment]
好了, 我添加了MIT许可证

**Comment by Jinky-X** [comment]
谢谢，祝你新春快乐
